### ISSUE TITLE
Item Simulation

### ISSUE THREAD

**Issue by BarrorL** [misaomaki/misaomaki.github.io#1]
Hi. Your existing simulators are really awesome. Could you also create a scrolling simulator where it lists the stat lines for an equipment in both the old and new UI layout?

Old:
![vss](https://user-images.githubusercontent.com/83960447/152420220-d8899c3d-04ec-499f-83ef-7c36232d6836.jpg)

New:
![tyrantcape](https://user-images.githubusercontent.com/83960447/152421920-adfc705c-348c-4fe5-bd80-9c4ccdf7abf4.png)

**Comment by misaomaki** [comment]
Thanks!

If I can find the UI elements for the old one (or someone can recreate it with CSS). Any reason why you'd want the old one?

**Comment by BarrorL** [comment]
> Thanks!
> 
> If I can find the UI elements for the old one (or someone can recreate it with CSS). Any reason why you'd want the old one?

Thank you for replying!

The old UI partially due to nostalgia for the old classic feel, but mainly because of its simplistic stats layout for all the scrolls, enhancement, and cubing during the Pre Big Bang era. The new UI is also nice in its own right, and makes it more interesting for more modern scrolling. Maybe making them toggle-able in which mode users prefer to view it in could be possible. Having both the old and the new just makes it so that there's something fun for everyone.

Perhaps also adding a functionality in the simulation where users can also manually select their desired cube lines, or edit their own scroll stats on an item to get what they want can also be a feature. Scrolls like Chaos Scroll are highly variable in nature and difficult to get the exact stats that users want, so maybe limit it within the min & max for the stats that the scroll allows. But if users want to roll the dice for it, they can as well.

I know it's a lot to ask, but I'm sure there are many out there that would like to relive the experience of scrolling some crazy end-game equipment; especially for the vast majority that never got to experience what it was like to be an AFK-er hanging out in Henesys Market with their crazy gear, which would very well be forever out of many's reach. Hopefully one day a comprehensive list with all possible equipment can be added to the simulator, and with the variability of above-average and below-average equipment from monster drops.

**Comment by misaomaki** [comment]
Can't seem to find the old UI stuff in the wz files. If it happens to pop up (maybe someone has old item.wz/ui.wz files?), I'll see what I can do.
