### ISSUE TITLE
This Bonus Potential Outcome Possible? Impossible?

### ISSUE THREAD

**Issue by BarrorL** [misaomaki/misaomaki.github.io#2]
I've been waiting for over 5 minutes for an outcome to happen. Is this bonus potential outcome ridiculously low, or is it impossible because there's a limit to how much primary stat % is allowed for a given piece of equipment?

![Commanding Earrings](https://user-images.githubusercontent.com/83960447/156909455-69deb344-b716-478f-9532-6c933334393f.png)

**Comment by misaomaki** [comment]
It's ridiculously low. If it were an impossible combo like triple boss damage on weapons, it would tell you at the start with an alert. Getting a prime bonus line is 0.0077% chance, so imagine trying to get 3 of them.

**Comment by BarrorL** [comment]
I see. For simplicity sake, assuming it's 0.023% for each prime bonus line, and that only one prime line exists (LUK: +8%) among other undesired prime lines, it would take over 82 billion cubes to reach that outcome.

Maybe a popup warning of insanely low probabilities of that magnitude could improve the user experience. It would beat waiting for something like that to come to fruition. Maybe even putting up the statistical number of cubes required to pull off such a feat in the warning would be nice, and then automatically add those lines onto the item.

**Comment by BarrorL** [comment]
I see. For simplicity sake, assuming it's 0.023% for each prime bonus line, and that only one prime line exists (LUK: +8%) while other prime lines don't exist for this example, it would take over 82 billion cubes to reach that outcome.

Maybe a popup warning of insanely low probabilities of that magnitude could improve the user experience. It would beat waiting for something like that to come to fruition. Maybe even putting up the statistical number of cubes required to pull off such a feat in the warning would be nice, and then automatically add those lines onto the item.

**Comment by misaomaki** [comment]
I can probably add the warning part if people are looking to do triple prime stuff, but the main point of the Auto Cube/Starforce feature is to generate log data. If you want to set the cubes directly, you can do so using the initial item popup options.
![image](https://user-images.githubusercontent.com/50785141/156971753-370b28c3-9380-4cfd-bc04-9b70bf8aa058.png)

**Comment by BarrorL** [comment]
Whoa! Is that item creation page new? It's great!

Also, I totally agree with the Auto function being meant for generating log data.

**Comment by misaomaki** [comment]
It's been there as part of the first screen you interact with. Granted, it's a little hidden since you have to scroll down after selecting an item. So on the todo list is just a simple warning for triple prime line shenanigans.
