### ISSUE TITLE
Add More Equips?

### ISSUE THREAD

**Issue by ghost** [misaomaki/misaomaki.github.io#3]
For the time being, could you add some fun old school equips? Maybe implement Chaos Scrolls as well?

Zakum Helmet, Horntail Necklace, Stormcaster Gloves, Pink Adventurer Cape, Maple Weapons, VIP Weapons, etc?

**Comment by misaomaki** [comment]
It may be tricky. Lower-level items have different cube lines and rates (which my cube rates code doesn't accommodate for). I think and the cubing code also doesn't accommodate for the lower tier stats it gives yet (right now only does tier 3 (12%, 9%, 9%) and tier 4 (13%, 10%, 10%) stats).

If you want to help out, you can add item data for me in the format at https://github.com/misaomaki/misaomaki.github.io/blob/master/starforce/item_db.js#L36

**Comment by BarrorL** [comment]
I wish I could do more to help, but I do not have any experience in programming, so I won't really know what I'm doing. I think I'd be doing more damage than anything productive.

For instance, I assume "mstat" has something to do with main stat, but not sure what "pstat" means. If it's a generic equip like a Bathrobe, this would be the extent of what I'd be able to do figure out based on the way you write your code:

>     common_overall: {
>         bathrobe_for_men_m: {
>             name: "Bathrobe for Men (M)",
>             level: 20,
>             class: "armor",
>             type: "overall",
>             speed: "",
>             job: ["beginner", "warrior", "magician", "bowman", "thief", "pirate"],
>             mstat: "", //assumed to be done correctly
>             pstat: [], //assumed to be done correctly
>             att_type: "att", 
>             flame_type: 0, //not exactly sure how to determine this
>             bstat: Object.assign({}, stats, {
>                 def: 20,
>                 speed: 10
>             }),
>             req: {
>                 str: 0,
>                 dex: 0,
>                 int: 0,
>                 luk: 0
>             },
>             img: "item-mrw",
>             upgrades: 10,
>             hammers_added: 2,
>         }
>     }

**Comment by BarrorL** [comment]
I wish I could do more to help, but I do not have any experience in programming, so I won't really know what I'm doing. I think I'd be doing more damage than anything productive.

For instance, I assume "mstat" has something to do with main stat, but not sure what "pstat" means. If it's a generic equip like a Bathrobe, this would be the extent of what I'd be able to do figure out based on the way you write your code:

>     common_overall: {
>         bathrobe_for_men_m: {
>             name: "Bathrobe for Men (M)",
>             level: 20,
>             class: "armor",
>             type: "overall",
>             speed: "",
>             job: ["beginner", "warrior", "magician", "bowman", "thief", "pirate"],
>             mstat: "", //assumed to be done correctly
>             pstat: [], //assumed to be done correctly
>             att_type: "att", 
>             flame_type: 0, //not exactly sure how to determine this
>             bstat: Object.assign({}, stats, {
>                 def: 20,
>                 speed: 10
>             }),
>             req: {
>                 str: 0,
>                 dex: 0,
>                 int: 0,
>                 luk: 0
>             },
>             img: "item-bathrobeformen", //assumed to be done correctly
>             upgrades: 10,
>             hammers_added: 2,
>         }
>     }

**Comment by misaomaki** [comment]
Thanks. It's less programming and more data entry work, so it won't be too hard. It's just tedious.

I have comments on the arcane dagger (which was the first item to be added). Probably should have linked that.
https://github.com/misaomaki/misaomaki.github.io/blob/master/starforce/item_db.js#L6202

mstat is the main stat. pstat is the primary stats that starforcing will add. So for thief items, it is luk and str items. For common-to-all-classes items, it is str, dex, int, and luk.

**Comment by misaomaki** [comment]
Before I add low-level equips, I'm going to redo the cubing logic as it is hardcoded to level 150/160 equips. With a better breakdown of how lines and levels related at https://strategywiki.org/wiki/MapleStory/Potential_System, it should handle any level item ok.
