### ISSUE TITLE
Marvel Machine Updates

### ISSUE THREAD

**Issue by BarrorL** [misaomaki/misaomaki.github.io#4]
Perhaps start making separate links to a specific Marvel Machine for all the updates that you've ever done so far from past, present, and onwards into the future instead of updating the code to present. Might help in preserving pieces of MapleStory history, at least for the Marvel Machine.

**Comment by misaomaki** [comment]
I usually keep 2 copies. marvel.html is the current one. marvel2.html is the previous one. marvel3.html is the one with frenzy.

Maybe I can. There's no harm in not doing it.
