### ISSUE TITLE
Can I apply the website to CMS（Chinese maplestory）

### ISSUE THREAD

**Issue by photonrain** [misaomaki/misaomaki.github.io#7]
Hello, I am a Chinese maplestory player. I am very excited to see your website, but the data on the website is not suitable for CMS. I hope to be able to conduct secondary development on your website, including adapting CMS data, translating, and adding new modules. Looking forward to your reply!

**Comment by misaomaki** [comment]
Go for it. Would love to see what you do!

**Comment by photonrain** [comment]
Thank you!
